# Generated by Django 3.1.7 on 2021-03-17 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=50)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crosscheckapi.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('full_name', models.CharField(max_length=150)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crosscheckapi.landlord')),
            ],
        ),
        migrations.CreateModel(
            name='TenantPropertyRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lease_start', models.DateField()),
                ('lease_end', models.DateField()),
                ('rent', models.IntegerField()),
                ('rented_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crosscheckapi.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crosscheckapi.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('ref_num', models.CharField(max_length=100)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crosscheckapi.landlord')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crosscheckapi.paymenttype')),
                ('rented_property', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crosscheckapi.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crosscheckapi.tenant')),
            ],
        ),
    ]
